name: Check PHP Code Style
on:
  push:
    branches-ignore:
      - 'master'
      - 'staging'
jobs:
  Check-Standards:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          tools: composer:v2
          coverage: none
      - name: Install Dependencies
        run: composer install
      - name: Run php-cs-fixer
        run: ./vendor/bin/php-cs-fixer fix --dry-run -v
      - name: Run Test Suite
        run: ./vendor/bin/phpunit
      - name: Run PhpStan
        run: ./vendor/bin/phpstan analyse
